// ios/Pods/VisionFaceDetector/VisionFaceDetectorPluginRegister.m

#import <VisionCamera/FrameProcessorPluginRegistry.h>
// This header is auto-generated by Xcode when you add a Swift file.
// It allows Objective-C code to see your Swift class.
#import "VisionFaceDetector-Swift.h"

// register the Swift plugin under the JS name "callback"
VISION_EXPORT_SWIFT_FRAME_PROCESSOR(VisionFaceDetector, callback)
